apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  config.yaml: |
    grpcScalerPort: {{ .Values.grpcScalerPort }}
    httpAPIPort: {{ .Values.httpAPIPort }}
    default:
      {{- toYaml .Values.default | nindent 6 }}
    {{- with .Values.metrics }}
    metrics:
      {{- toYaml . | nindent 6 }}
    {{- end }}
